---
- name: Create directory
  hosts: all
  tasks:
    - name: Create docker directory
      file:
        path: /opt/docker
        state: directory
        mode: "0755"
        owner: ubuntu
        group: ubuntu          

#     - name: Create playbooks directory
#       file:
#         path: /home/ubuntu/playbooks
#         state: directory
#         mode: "0755"
#         owner: ubuntu
#         group: ubuntu

    - name: Copy Dockerfile
      copy:
        src: ../Dockerfile
        dest: /opt/docker

    - name: Copy webapp.war
      copy:
        src: ../webapp/target/webapp.war
        dest: /opt/docker
