---
- name: DEPLOYMENT ON EKS
  hosts: all
  remote_user: root
  tasks:  
    - name: CREATE PLAYBOOKS DIR ON EKS CLUSTER
      file:
        path: /opt/playbooks/
        state: directory
        mode: "0755"      


    - name: COPY DEPLOYMENT FILE
      copy:
        src: /var/lib/jenkins/workspace/project-1/playbooks/dep_svc.yml
        dest: /opt/playbooks
        
        
    - name: DEPLOYMENT ON K8 CLUSTER
      shell: kubectl apply -f /opt/playbooks/dep_svc.yml; sleep 180

    - name: STATUS OF DEPLOYMENT
      shell: kubectl get pod
      register: get_deployment_status

    - name: PRINT DEPLOYMENT STATUS
      debug:
        var: get_deployment_status.stdout_lines

          
