---
- DEPLOYMENT ON EKS
  hosts: all
  remote_user: root
  tasks:  
    - name: Create playbook dir on EKS cluster
      file:
        path: /opt/playbooks/
        state: directory
        mode: "0755"      


    - name: Copy Deploymeny file.
      copy:
        src: /var/lib/jenkins/workspace/project-1/playbooks/dep_svc.yml
        dest: /opt/playbooks
        
        
    - name: Deployment on K8 Cluster
      shell: kubectl apply -f /opt/playbooks/dep_svc.yml
