---
- name: Deployment on K8 Cluster
  hosts: all
  tasks:
    - name: Deployment on K8 Cluster
      shell: |
        kubectl apply -f playbooks/eks_menifest.yml -u ubuntu
        sleep 10
        nohup kubectl port-forward --address 0.0.0.0 service/webapp-service 3000:80 &
